import Header from '@/components/Header'
import Head from 'next/head'
import '@/styles/globals.scss'
import headerStyles from '@/styles/components/Header.module.scss'
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function App({ Component, pageProps }) {
  const router = useRouter()

  useEffect(() => {
    if(router.pathname === "/"){
      document.querySelector(`.${headerStyles.header}`).classList.remove(headerStyles.white)
    }else{
      document.querySelector(`.${headerStyles.header}`).classList.add(headerStyles.white)
    }
  }, [router.pathname])

  return (
    <>
      <Head>
        <title>Alpine Escapes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <main>
        <Component {...pageProps}/>
      </main>
    </>
  )
}
